### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Rulox** [django-blog-zinnia/zinnia-theme-bootstrap#11]
Hi, I miss a little more of information about the installation. 
I have zinnia blog and bootstrap in installed apps:

I have installed zinnia via PIP and zinia_bootstrap via setup.py
INSTALLED_APPS = (
#... etc
    'zinnia_bootstrap',
    'zinnia',
)

What exactly do I have to put in TEMPLATE_LOADERS?

TEMPLATE_LOADERS = [
  #'zinnia.Loader',
  'django.template.loaders.eggs.Loader',
]

With this configuration I'm having:
TemplateDoesNotExist at /weblog/
zinnia:zinnia/base.html

PS: Zinnia worked perfectly before this.

Thanks and nice job!

**Comment by nim65s** [comment]
Hi,

Did you followed zinnia-theme-bootstrap's README and installed 
https://github.com/Fantomas42/django-app-namespace-template-loader ?

**Comment by Rulox** [comment]
Hi,
It was completely my fault, I had an error when installed Django Template App Namespace Template Loader and I didn't notice until now. I had a conflict with another package. It should work now.

Sorry for any inconvenience,
Greetings!
