### ISSUE TITLE
Doesn't work with Django 1.8

### ISSUE THREAD

**Issue by bradrice** [django-blog-zinnia/zinnia-theme-bootstrap#12]
When I try to use this with Django 1.8 or even 1.7 I cannot get blog enteries to display. It apparently displays the skeleton and base templates but then when I have an entry and click it, the entry does not appear.

Just Useful Links and Search appear.

http://lodiharrisvillehistorical.org/blog/

**Comment by Fantomas42** [comment]
Hello,

I have just tested with a recent version of Django, and everything works fine.

In your case, it seems that the view is correct, but the loaded template, is not. The content and title blocks are not filled by example.

Do you use custom templates ? I will close the issue until more informations.

Regards
