### ISSUE TITLE
.15.2 zinnia renames zinnia_tags to zinnia but this was not done in zinna-theme-bootstrap

### ISSUE THREAD

**Issue by opme** [django-blog-zinnia/zinnia-theme-bootstrap#13]
(venv2)michael@michael-OptiPlex-790:~/opme/venv2/lib/python2.7/site-packages$ grep -r zinnia_tags .
./django_blog_zinnia-0.15.2.dist-info/METADATA:* Rename ``zinnia_tags`` to ``zinnia``
./django_blog_zinnia-0.15.2.dist-info/DESCRIPTION.rst:* Rename ``zinnia_tags`` to ``zinnia``
./zinnia_bootstrap/templates/zinnia/entry_search.html:{% load i18n zinnia_tags %}
./zinnia_bootstrap/templates/zinnia/base.html:{% load zinnia_tags i18n %}
./zinnia_bootstrap/templates/zinnia/sitemap.html:{% load i18n zinnia_tags mptt_tags %}
./zinnia_bootstrap/templates/zinnia/entry_detail_base.html:{% load i18n zinnia_tags %}

**Comment by Fantomas42** [comment]
Hello, this change has already been done in https://github.com/django-blog-zinnia/zinnia-theme-bootstrap/commit/dc70fb96c8f31e83eaa157d151b21aa33a82438a

Do you use the v0.4 of zinnia-theme-bootstrap ?

Regards
