### ISSUE TITLE
Changing Zinnia body defaults not working

### ISSUE THREAD

**Issue by scotontheedge** [django-blog-zinnia/zinnia-theme-bootstrap#14]
Hi,

In the Zinnia documentation it say that there are a number of options to use dark, light, green, red, etc classes to override the defaults in the body via the skeleton.html.

I have tried to do this with your excellent theme and it doesn't seem to be working.

Can you advise if this is the correct behaviour?

Thanks,

Kenny

**Comment by Fantomas42** [comment]
Hello,

these options are only available on the default theme packaged with Zinnia, not in this package.

Regards
