### ISSUE TITLE
jQuery error for featured entry

### ISSUE THREAD

**Issue by ybendana** [django-blog-zinnia/zinnia-theme-bootstrap#15]
So far the bootstrap theme is working great, but I ran into this error when I made a featured entry: "Uncaught TypeError: undefined is not a function bootstrap.js".  It wasn't obvious from the code what the problem was. After some searching, it turned out that the culprit is the inclusion of jQuery in templates/tags/entries_slider.html.  Since I embed Zinnia in my own template and already include jQuery, this second inclusion caused the error.

**Comment by Fantomas42** [comment]
So if you use your own template, it's out of warranty :)

Simple solution: copy 'n' edit the problematic template to remove jquery.

Regards
