### ISSUE TITLE
lead vs continue-reading fonts

### ISSUE THREAD

**Issue by kriaa** [django-blog-zinnia/zinnia-theme-bootstrap#16]
Not sure where to ask this question. 

I have a django-blog running with bootstrap and I notice that the font of the 'entry-body' class after clicking the 'continue-reading' btn is still the same as the lead font in the previous page. I can see that the 'lead' class is being assigned to the text (after clicking continue-reading) instead of the 'continue-reading' class. I'd like to change this. i.e.

```
<div class="entry-content lead">
<p> loren epsom....</p>
</div>

```

How can I change this to 

```
<div class="entry-content continue-reading">
<p> loren epsom....</p>
</div>

```
The continue-reading class font is smaller than the lead class font.

Thank you.

**Comment by Fantomas42** [comment]
Sorry for the late reply.

If you want to change this behavior, you have to edit your own copy of templates/zinnia/_entry_detail_base.html 

And put something like this

        <div class="entry-content {% if continue_reading %}continue-reading{% else %}lead{% endif %}">


Regards
