### ISSUE TITLE
Invalid syntax for cycle tag in entry_detail_base.html

### ISSUE THREAD

**Issue by azaghal** [django-blog-zinnia/zinnia-theme-bootstrap#22]
Template `zinnia_bootstrap/templates/zinnia/entry_detail_base.html` makes a number of calls to the `cycle` tag using a wrong syntax.

Current syntax is:

```
{% cycle box1,box2 %}
```

Instead, the syntax should be:

```
{% cycle 'box1' 'box2' %}
```

This results in error `No named cycles in template. 'box1,box2' is not defined` when rendering the blog entry.

P.S.
I can create pull request if need be, although it's a tiny one :)

**Comment by Fantomas42** [comment]
Closed by #24

**Comment by patroqueeet** [comment]
is there a chance for a proper pypi release? otherwise I have to put develop branch into my dependencies... not the best approach though :)

**Comment by noahzaozao** [comment]
also want the pypi release please for this issue if possible, thanks @Fantomas42

**Comment by Fantomas42** [comment]
v0.5.2 published on Pypi

Regards

**Comment by Fantomas42** [comment]
v0.5.2 published on Pypi

Regards
