### ISSUE TITLE
Remove deprecated call to "load firstof from future"

### ISSUE THREAD

**Issue by azaghal** [django-blog-zinnia/zinnia-theme-bootstrap#23]
The syntax `load firstof from future` in template `zinnia_bootstrap/templates/comments/zinnia/entry/form.html` has been deprecated since Django version 1.8, and has been completely removed from Django 1.10.

When using the theme with Django 1.10, the following error is reported when comment form is rendered:

```
'future' is not a registered tag library. Must be one of:
```

It should be sufficient to remove `{% load firstof from future %}` to fix compatibility with Django 1.10.

**Comment by azaghal** [comment]
As per #22, I can create a pull request for this one if you're interested :)

**Comment by Fantomas42** [comment]
Closed by #24
