### ISSUE TITLE
Small problem when used with zinnia-theme-bootstrap

### ISSUE THREAD

**Issue by saintger** [django-blog-zinnia/zinnia-theme-bootstrap#3]
I tried  tried zinnia-theme-bootstrap (0.1) and it seems not compatible with zinnia-threaded-comments (0.1): the comment "reply" link to a comment doesn't appear.

Tested with Zinnia (0.12.3) and Django 1.5.1 On Debian Testing.

**Comment by keshavr7** [comment]
Is the current version of Zinnia-theme-bootstrap compatible with zinnia-threaded-comments ?

**Comment by Fantomas42** [comment]
It's just templating, so no incompatibilities should occur.
